#
#  ██████╗██╗     ██╗ ██████╗██╗  ██╗███████╗██████╗ ███████╗██████╗ ███████╗███████╗ ██████╗ ██████╗ ███╗   ██╗██████╗
# ██╔════╝██║     ██║██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝██╔═══██╗████╗  ██║██╔══██╗
# ██║     ██║     ██║██║     █████╔╝ ███████╗██████╔╝█████╗  ██████╔╝███████╗█████╗  ██║     ██║   ██║██╔██╗ ██║██║  ██║
# ██║     ██║     ██║██║     ██╔═██╗ ╚════██║██╔═══╝ ██╔══╝  ██╔══██╗╚════██║██╔══╝  ██║     ██║   ██║██║╚██╗██║██║  ██║
# ╚██████╗███████╗██║╚██████╗██║  ██╗███████║██║     ███████╗██║  ██║███████║███████╗╚██████╗╚██████╔╝██║ ╚████║██████╔╝
#  ╚═════╝╚══════╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═════╝
#
# Plugin made by dejvokep (https://dejvokep.dev/).
#
# ► Need any help?
# Join the Discord server (https://discord.com/invite/BbhADEy) and we will more than happily help you :)
#
# ► Placeholders (unknown replacement can be configured under placeholder.unknown-value):
# 1. Player:
#    - {uuid}: player's UUID
#    - {name}: player's name, or unknown if not available
#    - {id}: player's name, or UUID if not available
# 2. Info:
#    - {cps_best}: the best CPS
#    - {cps_best_date}: formatted date at which the best CPS were achieved (or unknown if the best CPS are 0)
#    - {cps_best_date_millis}: date in millis at which the best CPS were achieved (or unknown if the best CPS are 0)
#    - {cps_best_date_formatted}: alias for {cps_best_date}
#    - placeholders from the player group
# 3. All:
#    - {cps_now}: current CPS
#    - placeholders from the player and info groups
#
# Config version:
# - IMPORTANT >> Do NOT change unless you know what you are doing. Changing this might break the plugin.
config-version: 1
#
# Display:
# - PLACEHOLDERS >> All placeholders are available in the title, subtitle and messages. PlaceholderAPI placeholders can
#                   also be enabled under placeholder.allow-placeholder-api.
display:
  # Title display:
  # - IMPORTANT >> If on 1.8, ProtocolLib is required to run this display.
  title:
    # Enabled:
    enabled: false
    # Title to send during normal gameplay:
    normal:
      title: ""
      subtitle: "&b{cps_now} CPS"
    # Title to send while watching someone else (placeholders will be translated against the watched player):
    watching:
      title: ""
      subtitle: "&b{cps_now} CPS &7(watching {name})"
    # Refresh rate in ticks (delay between update):
    refresh: 20
  # Action bar display:
  # - IMPORTANT >> If on 1.8 or 1.9, ProtocolLib is required to run this display.
  action-bar:
    # Enabled:
    enabled: true
    # Messages:
    message:
      # Message to send during normal gameplay:
      normal: "&b{cps_now} CPS"
      # Message to send while watching someone else (placeholders will be translated against the watched player):
      watching: "&b{cps_now} CPS &7(watching {name})"
    # Refresh rate in ticks (delay between update):
    refresh: 20
  # Boss bar display:
  # - IMPORTANT >> If on 1.8, this display is not available.
  boss-bar:
    # Enabled:
    enabled: false
    # Color (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html):
    color: WHITE
    # Style (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html):
    style: SOLID
    # Flags (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarFlag.html):
    flags: [ ]
    # Progress (between 0 = empty and 1 = full):
    progress: 1
    # Messages:
    message:
      # Message to send during normal gameplay:
      normal: "&b{cps_now} CPS"
      # Message to send while watching someone else (placeholders will be translated against the watched player):
      watching: "&b{cps_now} CPS &7(watching {name})"
    # Refresh rate in ticks (delay between update):
    refresh: 20
#
# Placeholders:
placeholder:
  # Allow PlaceholderAPI placeholder translations in displayed messages:
  allow-placeholder-api: false
  # Replacement for unknown data:
  unknown-value: "?"
  # Date format (see https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)
  date-format: "yyyy/MM/dd HH:mm"
#
# Sampling rate in ticks:
# - INFO >> The lower sampling rate, the higher the demands for server processing power. Rate of 0 indicates immediate
#           sampling, which will compute CPS non-stop according to your clicks (the best user experience). Rates 1 and
#           higher represent rated sampling, which simply divides time into periods (each equally long according to the
#           rate) and then computes CPS from the amount of times you've clicked during that period.
# - IMPORTANT >> Use of values between 0 and 20 will lead to imprecise calculations, you should avoid those rates. Use
#                only 0, 20 or higher. Make sure to update the display refresh rates, so they do not bottleneck the
#                sampling capabilities.
sampling-rate: 20
async-process: true
#
# Messages:
messages:
  # Players only:
  players-only: "&7[&bCPS&7] &cCommand only for players."
  # Invalid name (when name has been used as the parameter but the referenced player has not yet played on the server):
  # - PLACEHOLDERS >> {name}: the provided name
  invalid-name: "&7[&bCPS&7] &cCould not obtain UUID from player '{name}', has he played on the server already?"
  # Data request:
  data-request:
    # Sent:
    sent: "&7[&bCPS&7] &7Data request was sent, please wait..."
  # /cps confirm:
  confirm:
    # Confirmation required:
    required: "&7[&bCPS&7] &7Confirmation required! Please use &b/cps confirm &7within &b20 seconds &7to confirm the operation."
    # No confirmation pending:
    not-pending: "&7[&bCPS&7] &cThere are not any pending confirmations."
  # /cps watch [name]:
  watch:
    # Error:
    error:
      # Attempting to watch an offline player:
      # - PLACEHOLDERS >> {name}: the provided name
      player-offline: "&7[&bCPS&7] &cPlayer {name} is offline."
      # Attempting to watch yourself:
      yourself: "&7[&bCPS&7] &cYou cannot watch yourself."
      # Attempting to stop, but not watching anyone:
      not-watching: "&7[&bCPS&7] &cYou are not watching anyone."
    # Started watching:
    # - PLACEHOLDERS >> player group
    start: "&7[&bCPS&7] &bStarted &7watching player &b{name}&7. Use this command again to toggle off."
    # Stopped watching:
    # - PLACEHOLDERS >> player group
    stop: "&7[&bCPS&7] &bStopped &7watching player &b{name}&7."
    # Automatically stopped watching because the player disconnected:
    # - PLACEHOLDERS >> player group
    disconnected: "&7[&bCPS&7] &bStopped &7watching player &b{name} &7- player disconnected."
  # /cps delete <name|uuid|all>:
  delete: "&7[&bCPS&7] &7Deleted the requested data."
  # /cps reload:
  reload: "&7[&bCPS&7] &7Plugin reloaded."